@host=https://flj-671w.onrender.com


GET {{host}}/clientes
###
GET {{host}}/clientes/7
###
POST {{host}}/clientes
content-type: application/json

{
    "nome": "João Cleber Sobral",
    "telefone1": "83987657531",
    "telefone2": "83991358853",
    "email": "jcs@email.com"
}

###
PATCH {{host}}/clientes/3
Content-Type: application/json

{
  "nome": "Fernanda Cabral de Lima"
}

###
DELETE {{host}}/clientes/2

###
GET {{host}}/clientes/nome/cleber

###
POST {{host}}/clientes/6/enderecos
Content-Type: application/json

{
  "cep":"58000000",
  "logradouro":"Rua diogenes dias",
  "numero":"33",
  "bairro":"Mangabeira",
  "cidade":"João Pessoa",
  "estado":"PB"
}

###
POST {{host}}/clientes/7/veiculos
Content-Type: application/json

{
  "marca":"fiat",
  "modelo":"uno",
  "ano":"1990",
  "placa":"abc1234"
}
